# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_clientes = QtWidgets.QLabel(self.centralwidget)
        self.lbl_clientes.setGeometry(QtCore.QRect(200, 30, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lbl_clientes.setFont(font)
        self.lbl_clientes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_clientes.setStyleSheet("QLabel{\n"
"font: 75 12pt \"Hack\";\n"
"color:\'white\';\n"
"background-color:\'blue\'\n"
"\n"
"}\n"
"\n"
"")
        self.lbl_clientes.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_clientes.setObjectName("lbl_clientes")
        self.btn_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_aceptar.setGeometry(QtCore.QRect(220, 370, 133, 23))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setBold(True)
        font.setWeight(75)
        self.btn_aceptar.setFont(font)
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.btn_salir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_salir.setGeometry(QtCore.QRect(360, 370, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_salir.setFont(font)
        self.btn_salir.setObjectName("btn_salir")
        self.lbl_DNI = QtWidgets.QLabel(self.centralwidget)
        self.lbl_DNI.setGeometry(QtCore.QRect(60, 100, 21, 16))
        self.lbl_DNI.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_DNI.setObjectName("lbl_DNI")
        self.txt_DNI = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_DNI.setGeometry(QtCore.QRect(90, 100, 113, 20))
        self.txt_DNI.setObjectName("txt_DNI")
        self.lbl_validoDNI = QtWidgets.QLabel(self.centralwidget)
        self.lbl_validoDNI.setGeometry(QtCore.QRect(230, 100, 47, 13))
        self.lbl_validoDNI.setText("")
        self.lbl_validoDNI.setObjectName("lbl_validoDNI")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setCheckable(True)
        self.actionSalir.setObjectName("actionSalir")
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IMPORT - EXPORT TEIS"))
        self.lbl_clientes.setText(_translate("MainWindow", "XESTION CLIENTES"))
        self.btn_aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btn_salir.setText(_translate("MainWindow", "Salir"))
        self.lbl_DNI.setText(_translate("MainWindow", "DNI:"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Alt+S"))
